package com.abnamro.recipe.web;

import java.util.List;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.springframework.data.domain.Page;

import com.abnamro.recipe.api.model.Ingredient;
import com.abnamro.recipe.api.model.IngredientPage;
import com.abnamro.recipe.api.model.IngredientType;

/**
 * Maps between the persistence-layer {@link com.abnamro.recipe.model.Ingredient}
 * aggregate and the OpenAPI-generated DTOs. The domain types are referenced by
 * fully-qualified name because their simple names clash with the generated DTOs.
 * Enum conversions ({@code IngredientType}) are generated by name and are null-safe.
 */
@Mapper(componentModel = "spring")
public interface IngredientMapper {

    /** Domain ingredient → API DTO. Exposes {@code publicId} as the API {@code id}. */
    @Mapping(target = "id", source = "publicId")
    Ingredient toDto(com.abnamro.recipe.model.Ingredient entity);

    /** A page of domain ingredients → the API {@code IngredientPage}. */
    default IngredientPage toPageDto(Page<com.abnamro.recipe.model.Ingredient> page) {
        List<Ingredient> content = page.getContent().stream().map(this::toDto).toList();
        return new IngredientPage(
                content,
                page.getNumber(),
                page.getSize(),
                page.getTotalElements(),
                page.getTotalPages(),
                page.isFirst(),
                page.isLast());
    }

    /** API enum → domain enum (constant names are identical). Null-safe for filters. */
    com.abnamro.recipe.model.IngredientType toDomainType(IngredientType type);
}
