package com.abnamro.recipe.web;

import java.util.Comparator;
import java.util.List;

import org.mapstruct.AfterMapping;
import org.mapstruct.IterableMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValueMappingStrategy;
import org.springframework.data.domain.Page;

import com.abnamro.recipe.api.model.DietaryProfile;
import com.abnamro.recipe.api.model.Recipe;
import com.abnamro.recipe.api.model.RecipeIngredient;
import com.abnamro.recipe.api.model.RecipeIngredientSelection;
import com.abnamro.recipe.api.model.RecipePage;
import com.abnamro.recipe.model.DietaryFlag;
import com.abnamro.recipe.service.dto.IngredientSelectionDto;
import com.abnamro.recipe.service.dto.RecipeDto;

/**
 * Maps between the persistence-layer recipe read model ({@link RecipeDto}) and the
 * OpenAPI-generated DTOs. Domain types are referenced by fully-qualified name because
 * their simple names clash with the generated DTOs. Enum conversions ({@code MeasurementUnit})
 * are generated by name.
 */
@Mapper(componentModel = "spring")
interface RecipeMapper {

    /** A recipe dto with its pre-joined ingredients → the API {@code Recipe} DTO. */
    @Mapping(target = "id", source = "publicId")
    Recipe toDto(RecipeDto dto);

    /** Sorts the mapped ingredients case-insensitively by name (MapStruct does not sort). */
    @AfterMapping
    default void sortIngredients(@MappingTarget Recipe recipe) {
        recipe.getIngredients()
                .sort(Comparator.comparing(RecipeIngredient::getName, String.CASE_INSENSITIVE_ORDER));
    }

    @Mapping(target = "ingredientId", source = "publicId")
    RecipeIngredient toIngredientDto(RecipeDto.Ingredient ingredient);

    /** Domain dietary profile → API DTO. Flags are read via {@code is(...)}, so this is hand-written. */
    default DietaryProfile toProfileDto(com.abnamro.recipe.model.DietaryProfile profile) {
        return new DietaryProfile(
                profile.is(DietaryFlag.VEGETARIAN),
                profile.is(DietaryFlag.VEGAN),
                profile.is(DietaryFlag.MEAT),
                profile.is(DietaryFlag.GLUTEN),
                profile.is(DietaryFlag.WHEAT),
                profile.is(DietaryFlag.NUT));
    }

    /** A page of recipe dtos → the API {@code RecipePage}. */
    default RecipePage toPageDto(Page<RecipeDto> page) {
        List<Recipe> content = page.getContent().stream().map(this::toDto).toList();
        return new RecipePage(
                content,
                page.getNumber(),
                page.getSize(),
                page.getTotalElements(),
                page.getTotalPages(),
                page.isFirst(),
                page.isLast());
    }

    /** API create-request selections → domain selections (enum converted, null → empty list). */
    @IterableMapping(nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
    List<IngredientSelectionDto> toDomainSelections(List<RecipeIngredientSelection> selections);

    IngredientSelectionDto toDomainSelection(RecipeIngredientSelection selection);
}
